from pathlib import Path

# Final visible-text cleanup. Internal protocol/status/JSON keys remain unchanged.

p = Path('app/src/main/java/com/rui/astockstrategy/v6/V6Activity.kt')
s = p.read_text(encoding='utf-8')

# Known visible remnants after all earlier patches.
for a, b in {
    'B4组合实时跟踪': '综合确认池实时跟踪',
    'ETF申赎': '指数基金一级申赎',
    '次一交易日开盘起 Forward Tracking': '次一交易日开盘起后续收益跟踪',
    'Key("Forward Tracking",': 'Key("后续收益跟踪",',
    '参考 Tracking': '参考收益跟踪',
    '这是 Preview': '这是盘中预览',
    'Preview，不写入历史': '盘中预览，不写入历史',
    '暂无 Official Snapshot': '暂无正式冻结快照',
    'Official Snapshot': '正式冻结快照',
    'Latest Official': '最新正式冻结结果',
}.items():
    s = s.replace(a, b)

# Do not expose transport/debug English in the market-error card.
s = s.replace(
    'Notice("请求异常：行情 ${quoteError ?: "OK"}；板块 ${boardError ?: "OK"}。页面会明确标记 stale，不再把旧值伪装成 Live。")',
    'Notice("行情或板块数据源出现异常；页面会明确标记数据新鲜度，不会把旧数据伪装成实时行情。")'
)

# Factor availability is backend text and may contain internal B-codes. Translate it at render time.
s = s.replace(
    'Text(missing.entries.joinToString(" · ") { "${it.key}: ${it.value}" }, fontSize = 8.sp, color = Amber, maxLines = 4)',
    'Text(missing.entries.joinToString(" · ") { "${poolTitle(it.key)}：${factorTextZh(it.value)}" }, fontSize = 8.sp, color = Amber, maxLines = 4)'
)

# Audit issue codes are internal evidence keys and must never leak English to the UI.
s = s.replace(
    's.auditIssues.joinToString(" · ")',
    's.auditIssues.joinToString(" · ") { auditIssueZh(it) }'
)

marker = '@Composable\nfun PerformanceCard(title: String, p: JSONObject?) {'
if marker in s and 'fun auditIssueZh(' not in s:
    helpers = '''fun factorTextZh(v: String): String = v\n    .replace("B0", "基础强势池")\n    .replace("B1", "两融增强池")\n    .replace("B2", "指数基金一级申赎资金池")\n    .replace("B3", "主力资金确认池")\n    .replace("B4", "综合确认池")\n    .replace("ETF", "交易型开放式指数基金")\n\nfun auditIssueZh(v: String): String = when {\n    v.startsWith("raw-price-cross-source-incomplete") -> "原始价格跨数据源核对不完整" + v.substringAfter(':', "").let { if (it.isBlank()) "" else "（$it）" }\n    v == "point-in-time-constituent-snapshot-missing" -> "缺少时点成分股冻结快照"\n    v == "missing-strategy-version" -> "缺少策略版本记录"\n    v.startsWith("missing-stock-metadata") -> "个股元数据缺失" + v.substringAfter(':', "").let { if (it.isBlank()) "" else "（$it）" }\n    v.contains("margin", true) -> "两融数据来源证据不足"\n    v.contains("etf", true) -> "指数基金一级申赎数据来源证据不足"\n    v.contains("price", true) -> "价格数据核对证据不足"\n    v.contains("source", true) || v.contains("provenance", true) -> "数据来源证据不足"\n    else -> "数据审计项待核对"\n}\n\n'''
    s = s.replace(marker, helpers + marker, 1)

p.write_text(s, encoding='utf-8')

# Yunai/Quant/API are user-facing brand/technical English in this small status component.
y = Path('app/src/main/java/com/rui/astockstrategy/v6/YunaiGatewayStatus.kt')
ys = y.read_text(encoding='utf-8')
ys = ys.replace('Key("Yunai Quant API", label)', 'Key("云AI量化数据接口", label)')
ys = ys.replace('Key("Yunai市场状态",', 'Key("云AI量化市场状态",')
ys = ys.replace('if (!s.openapiState.isNullOrBlank()) Key("Yunai接口发现", s.openapiState)', '''if (!s.openapiState.isNullOrBlank()) {\n            val discovery = when (s.openapiState.lowercase()) {\n                "ready", "ok", "success" -> "已就绪"\n                "unavailable", "failed", "error" -> "不可用"\n                else -> "已读取"\n            }\n            Key("云AI量化接口发现", discovery)\n        }''')
y.write_text(ys, encoding='utf-8')

# Post-close dashboard: translate the status rather than printing raw "Official".
pc = Path('app/src/main/java/com/rui/astockstrategy/v6/PostCloseDashboard.kt')
ps = pc.read_text(encoding='utf-8')
ps = ps.replace('${official.date} ${official.status}', '${official.date} ${zhStatus(official.status)}')
pc.write_text(ps, encoding='utf-8')

# Historical replay / detail / tail known visible technical labels.
h = Path('app/src/main/java/com/rui/astockstrategy/v6/HistoricalReplay.kt')
hs = h.read_text(encoding='utf-8')
for a, b in {
    'RS20': '20日相对强弱',
    'RS60': '60日相对强弱',
    'MTA': '多周期趋势一致性',
    'Alpha': '超额收益',
    'ETF': '交易型开放式指数基金',
}.items():
    # HistoricalReplay has no protocol keys named with these labels in the current build;
    # the replacements here are therefore limited to display text generated by prior patches.
    hs = hs.replace(a, b)
h.write_text(hs, encoding='utf-8')

# Version polish release after 2.1.0.
g = Path('app/build.gradle.kts')
gs = g.read_text(encoding='utf-8')
gs = gs.replace('versionCode = 22', 'versionCode = 23')
gs = gs.replace('versionName = "2.1.0"', 'versionName = "2.1.1"')
g.write_text(gs, encoding='utf-8')
